version: '2'

services:
  db:
    image: sarataha/oreilly-couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    networks:
      - jenkins

  app:
    build: ./webapp
    image: sarataha/docker-jenkins-app

  app2:
    image: sarataha/docker-jenkins-java-pipeline:${BUILD_NUMBER}
    networks:
      - jenkins

  unit:
    image: maven
    volumes:
      - .:/usr/src/myapp
      - /tmp/go:/go
    command: bash -c "mvn test"

